#!/usr/bin/env python3
"""Generate and verify `docs/adr/README.md` indexes across the Atlas stack.

Per AGENTS.md `context_and_memory: ADR governance`, every ADR directory
carries an index — number, title, status per ADR — updated in the same change
as any ADR it lists. Hand-maintained indexes rot, so the index is derived
state under the generator contract: regeneration is idempotent, the output is
derived only from ADR headers, and `check` mode fails on drift so CI can gate
freshness exactly like the stack overlay.

Two modes:

    generate  rewrite every index from the ADR files on disk
    check     regenerate in memory and diff against disk; nonzero exit on
              drift or a missing index

Anomalies (duplicate numbers, missing or non-canonical statuses) are reported
on stdout in both modes; fixing them is board burn-down, not this script's
job — the index records the corpus as it is.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ATLAS_ROOT = Path(__file__).resolve().parent.parent
CANONICAL = {"Proposed", "Accepted", "Rejected"}
STATUS_RE = re.compile(r"^\s*Status:\s*(.+?)\s*$", re.MULTILINE)
STATUS_HEADING_RE = re.compile(r"^##\s*Status\s*\n+\s*([A-Za-z][^\n]*?)\s*$", re.MULTILINE)
TITLE_RE = re.compile(r"^#\s+(?:ADR[- ]?\d+\s*[:\-]\s*)?(.+?)\s*$", re.MULTILINE)
NUMBER_RE = re.compile(r"^(\d+)")

HEADER = """# ADR index

<!-- Generated by scripts/adr-index.py — do not hand-edit.
     Regenerate:  python scripts/adr-index.py generate
     Check:       python scripts/adr-index.py check -->

| ADR | Title | Status |
| --- | ----- | ------ |
"""


def adr_dirs() -> list[Path]:
    dirs = []
    meta = ATLAS_ROOT / "docs" / "adr"
    if meta.is_dir():
        dirs.append(meta)
    repos = ATLAS_ROOT / "repos"
    if repos.is_dir():
        for repo in sorted(repos.iterdir()):
            d = repo / "docs" / "adr"
            if d.is_dir():
                dirs.append(d)
    return dirs


def parse_adr(path: Path) -> tuple[str, str, str]:
    """Return (number, title, status) as recorded, without correcting them."""
    number_match = NUMBER_RE.match(path.name)
    number = number_match.group(1) if number_match else "—"
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:1200]
    except OSError:
        return number, path.stem, "—"
    title_match = TITLE_RE.search(head)
    title = title_match.group(1) if title_match else path.stem
    status_match = STATUS_RE.search(head) or STATUS_HEADING_RE.search(head)
    status = status_match.group(1) if status_match else "—"
    return number, title, status


def build_index(directory: Path) -> tuple[str, list[str]]:
    rows: list[str] = []
    anomalies: list[str] = []
    seen: dict[str, str] = {}
    files = sorted(
        f for f in directory.glob("*.md") if f.name.lower() != "readme.md"
    )
    for f in files:
        number, title, status = parse_adr(f)
        base = status.split("-", 1)[0].split(" ", 1)[0]
        if status == "—":
            anomalies.append(f"missing status: {f.name}")
        elif base.capitalize() not in CANONICAL:
            anomalies.append(f"non-canonical status {status!r}: {f.name}")
        elif base not in CANONICAL:
            anomalies.append(f"status casing {status!r}: {f.name}")
        if number != "—":
            if number in seen:
                anomalies.append(
                    f"duplicate number {number}: {f.name} and {seen[number]}"
                )
            else:
                seen[number] = f.name
        title = title.replace("|", "\\|")
        rows.append(f"| [{number}]({f.name}) | {title} | {status} |")
    return HEADER + "\n".join(rows) + "\n", anomalies


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=["generate", "check"])
    mode = parser.parse_args().mode

    drift = 0
    for directory in adr_dirs():
        content, anomalies = build_index(directory)
        rel = directory.relative_to(ATLAS_ROOT)
        index = directory / "README.md"
        for a in anomalies:
            print(f"{rel}: {a}")
        if mode == "generate":
            existing = index.read_text(encoding="utf-8") if index.exists() else None
            if existing != content:
                index.write_text(content, encoding="utf-8", newline="\n")
                print(f"{rel}: index written")
        else:
            if not index.exists():
                print(f"{rel}: MISSING index")
                drift += 1
            elif index.read_text(encoding="utf-8") != content:
                print(f"{rel}: index DRIFTED from ADR headers")
                drift += 1
    if mode == "check" and drift:
        print(f"{drift} index(es) missing or stale")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
