#!/usr/bin/env python3
"""Generate and verify `docs/adr/README.md` indexes across the Atlas stack.

Per AGENTS.md `context_and_memory: ADR governance`, every ADR directory
carries an index — number, title, status per ADR — updated in the same change
as any ADR it lists. Hand-maintained indexes rot, so the index is derived
state under the generator contract: regeneration is idempotent, the output is
derived only from ADR headers, and `check` mode fails on drift so CI can gate
freshness exactly like the stack overlay.

Two modes:

    generate  rewrite every index from the ADR files on disk
    check     regenerate in memory and diff against disk; nonzero exit on
              drift or a missing index

Anomalies (duplicate numbers, missing or non-canonical statuses) are reported
on stdout in both modes; fixing them is board burn-down, not this script's
job — the index records the corpus as it is.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ATLAS_ROOT = Path(__file__).resolve().parent.parent
CANONICAL = {"Proposed", "Accepted", "Rejected"}
STATUS_RE = re.compile(r"^\s*(?:-\s+)?Status\s*:\s*(.+?)\s*$", re.MULTILINE)
STATUS_BOLD_RE = re.compile(
    r"^\s*(?:-\s+)?\*\*Status(?:\*\*\s*:|\s*:\*\*)\s*(.+?)\s*$", re.MULTILINE
)
STATUS_HEADING_RE = re.compile(r"^##\s*Status\s*\n+\s*([A-Za-z][^\n]*?)\s*$", re.MULTILINE)
TITLE_RE = re.compile(
    r"^#\s+(?:ADR[- ]?\d+\s*(?:[:\-]|–|—)\s*)?(.+?)\s*$", re.MULTILINE
)
NUMBER_RE = re.compile(r"^(\d+)")

HEADER = """# ADR index

<!-- Generated by scripts/adr-index.py — do not hand-edit.
     Regenerate:  python scripts/adr-index.py generate
     Check:       python scripts/adr-index.py check -->

| ADR | Title | Status |
| --- | ----- | ------ |
"""

NON_ADR_MARKDOWN = frozenset({"readme.md", "index.md"})


def adr_dirs() -> list[Path]:
    dirs = []
    meta = ATLAS_ROOT / "docs" / "adr"
    if meta.is_dir():
        dirs.append(meta)
    repos = ATLAS_ROOT / "repos"
    if repos.is_dir():
        for repo in sorted(repos.iterdir()):
            d = repo / "docs" / "adr"
            if d.is_dir():
                dirs.append(d)
    return dirs


def status_base(status: str) -> str:
    """First canonical-status token of a recorded status line, Markdown stripped.

    ADRs annotate statuses with Markdown bold, hyphenated phases, and sign-off
    narrative; the index records only the canonical token (`**Accepted** - ...`
    -> `Accepted`). A missing status ("—") maps to itself.
    """
    return status.split("-", 1)[0].split(" ", 1)[0].strip("*` ").strip()


def parse_adr(path: Path) -> tuple[str, str, str]:
    """Return (number, title, status) as recorded, without correcting them."""
    number_match = NUMBER_RE.match(path.name)
    number = number_match.group(1) if number_match else "—"
    try:
        head = path.read_text(encoding="utf-8", errors="replace")[:1200]
    except OSError:
        return number, path.stem, "—"
    title_match = TITLE_RE.search(head)
    title = title_match.group(1) if title_match else path.stem
    status_match = (
        STATUS_RE.search(head)
        or STATUS_BOLD_RE.search(head)
        or STATUS_HEADING_RE.search(head)
    )
    status = status_match.group(1) if status_match else "—"
    return number, title, status


def tracked_markdown(directory: Path) -> set[str] | None:
    """Names of the `.md` files Git actually tracks in `directory`.

    The index is a set of links a reader follows after cloning, so it must be
    built from the tracked tree rather than from the author's disk. Building
    it from `glob` alone let an untracked file satisfy an index entry: ADR
    0045 was deleted from `HEAD` twice by unrelated commits while remaining
    on disk, and this gate reported the index clean both times, so a fresh
    clone had a dead link where CI was green.

    Reads `HEAD`, not the index. The index is working state: a peer's staged
    deletion, or a commit written through a private index, leaves an entry
    absent from `git ls-files` while `HEAD` still carries it. Asking the index
    produced three false "untracked" reports on first run -- coeus 0066,
    hephaestus 0052 and leto 0026 were all present in `HEAD` and on disk. What
    a fresh clone receives is `HEAD`, so that is the oracle.

    Returns `None` when Git cannot answer -- an unpacked tarball, say -- in
    which case the caller falls back to the on-disk view rather than
    reporting every ADR as untracked.
    """
    try:
        out = subprocess.run(
            ["git", "-C", str(directory), "ls-tree", "--name-only", "HEAD", "--", "."],
            capture_output=True, text=True, check=True,
        ).stdout
    except (OSError, subprocess.CalledProcessError):
        return None
    return {Path(line).name for line in out.splitlines() if line.strip()}


def commits_behind_upstream(directory: Path) -> int:
    """How many commits this checkout is behind its tracked upstream.

    Findings are reported against whatever revision happens to be checked
    out, and members of this stack are routinely behind: eight of
    twenty-five were, the day this was added. A stale checkout then
    manufactures drift that upstream already fixed — coeus reported a
    missing ADR 0066 index row that `origin/main` had carried for six
    commits. Stating the distance turns that from a defect report into an
    attributable one.

    Falls back to `origin/main` when `@{upstream}` does not resolve, which
    is the common case here rather than an edge one: a detached HEAD has no
    upstream, and detached checkouts are exactly the stale ones this is
    meant to catch — coeus was six behind on a detached HEAD.

    Zero when neither resolves, so the note only appears when it means
    something.
    """
    for rev in ("@{upstream}", "origin/main"):
        try:
            out = subprocess.run(
                ["git", "-C", str(directory), "rev-list", "--count", f"HEAD..{rev}"],
                capture_output=True, text=True, check=True,
            ).stdout.strip()
        except (OSError, subprocess.CalledProcessError):
            continue
        if out.isdigit():
            return int(out)
    return 0


def build_index(directory: Path) -> tuple[str, list[str]]:
    rows: list[str] = []
    anomalies: list[str] = []
    seen: dict[str, str] = {}
    tracked = tracked_markdown(directory)
    files = sorted(
        f for f in directory.glob("*.md") if f.name.lower() not in NON_ADR_MARKDOWN
    )
    if tracked is not None:
        untracked = [f for f in files if f.name not in tracked]
        for f in untracked:
            anomalies.append(
                f"untracked, so absent from a fresh clone: {f.name}"
            )
        files = [f for f in files if f.name in tracked]
    for f in files:
        number, title, status = parse_adr(f)
        base = status_base(status)
        if status == "—":
            anomalies.append(f"missing status: {f.name}")
        elif base.capitalize() not in CANONICAL:
            anomalies.append(f"non-canonical status {status!r}: {f.name}")
        elif base not in CANONICAL:
            anomalies.append(f"status casing {status!r}: {f.name}")
        if number != "—":
            if number in seen:
                anomalies.append(
                    f"duplicate number {number}: {f.name} and {seen[number]}"
                )
            else:
                seen[number] = f.name
        title = title.replace("|", "\\|")
        rows.append(f"| [{number}]({f.name}) | {title} | {base} |")
    return HEADER + "\n".join(rows) + "\n", anomalies


def _staleness_note(directory: Path) -> str:
    """Suffix naming how far behind upstream the reporting checkout is."""
    behind = commits_behind_upstream(directory)
    if not behind:
        return ""
    return (
        f" (checkout is {behind} commit(s) behind upstream; "
        "confirm against the current revision before treating this as a defect)"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=["generate", "check"])
    mode = parser.parse_args().mode

    drift = 0
    for directory in adr_dirs():
        content, anomalies = build_index(directory)
        rel = directory.relative_to(ATLAS_ROOT)
        index = directory / "README.md"
        for a in anomalies:
            print(f"{rel}: {a}")
        if mode == "generate":
            existing = index.read_text(encoding="utf-8") if index.exists() else None
            if existing != content:
                index.write_text(content, encoding="utf-8", newline="\n")
                print(f"{rel}: index written")
        else:
            if not index.exists():
                print(f"{rel}: MISSING index{_staleness_note(directory)}")
                drift += 1
            elif index.read_text(encoding="utf-8") != content:
                print(f"{rel}: index DRIFTED from ADR headers{_staleness_note(directory)}")
                drift += 1
    if mode == "check" and drift:
        print(f"{drift} index(es) missing or stale")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
