#!/usr/bin/env python3
"""Generate and verify the Atlas stack development overlay.

The overlay is the single `[patch]` block in the stack-root `.cargo/config.toml`
that redirects first-party git dependencies to the local working trees. It lives
at the root because a `[patch]` section in a *member* manifest is only honored
when that member is the root of the build -- Cargo ignores it whenever the
member is consumed as a dependency. A root config `[patch]` applies to every
build beneath the root, which is the actual requirement.

Member manifests therefore keep their `git + version` sources and stay
consumable as git dependencies; this file owns local resolution.

Two modes:

    generate  rewrite the overlay block in .cargo/config.toml from the real
              repository layout (never hand-curated)
    check     report version lag -- every first-party requirement that the
              current local trees cannot satisfy. A patch only unifies when the
              local version satisfies the declared requirement, so lag is what
              produces the "local X cannot replace git-sourced Y" resolver
              failure.

Exit status is nonzero when `check` finds lag, so CI can gate on it.
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from atlas_stack import registered_member_names  # noqa: E402

ATLAS_ROOT = Path(__file__).resolve().parent.parent
REPOS = ATLAS_ROOT / "repos"
CONFIG = ATLAS_ROOT / ".cargo" / "config.toml"

BEGIN = "# >>> atlas stack development overlay (generated) >>>"
END = "# <<< atlas stack development overlay (generated) <<<"

FIRST_PARTY_HOST = "github.com/ryancinsight/"

HEADER = f"""{BEGIN}
# Generated by scripts/atlas-stack-overlay.py -- do not hand-edit.
#
# Redirects every first-party git dependency to its local working tree, for all
# builds rooted anywhere beneath the Atlas root. Member manifests keep their
# `git + version` sources, so each repository still resolves standalone and in
# CI exactly as published.
#
# A `[patch]` section committed in a member manifest does NOT do this: Cargo
# honors manifest patches only in the root manifest of the build, so such a
# block is inert for every downstream consumer while making the member
# unconsumable as a clean git dependency.
#
# Local builds rewrite member `Cargo.lock` files (the `source` line is dropped
# and `[[patch.unused]]` entries appear). That churn is a development artifact:
# never commit it. Release and CI resolution is verified with `--locked` from a
# clean checkout, where this overlay does not apply.
#
# Regenerate:  python scripts/atlas-stack-overlay.py generate
# Check lag:   python scripts/atlas-stack-overlay.py check
"""


def _skip(path: Path) -> bool:
    parts = {p.lower() for p in path.parts}
    return bool(parts & {"target", ".git", "node_modules"})


def repo_manifests() -> list[Path]:
    """Return manifests from the authoritative registered-repo namespace only.

    ``worktrees/`` and other lane copies are intentionally excluded: the root
    overlay is a development view of the canonical ``repos/`` checkouts, not a
    package resolver for alternate working copies.
    """
    manifests: set[Path] = set()
    for member in registered_member_names():
        root = REPOS / member
        if not root.is_dir():
            continue
        manifests.update(
            manifest for manifest in root.glob("**/Cargo.toml") if not _skip(manifest)
        )
    return sorted(manifests)


def load_packages() -> dict[str, tuple[Path, str | None]]:
    """Map local package name -> (path relative to ATLAS_ROOT, version)."""
    packages: dict[str, tuple[Path, str | None]] = {}
    workspace_versions: dict[Path, str] = {}

    manifests = repo_manifests()

    for manifest in sorted(set(manifests)):
        try:
            data = tomllib.loads(manifest.read_text(encoding="utf-8"))
        except (tomllib.TOMLDecodeError, OSError):
            continue
        ws = data.get("workspace", {}).get("package", {})
        if "version" in ws:
            workspace_versions[manifest.parent] = ws["version"]

    for manifest in sorted(set(manifests)):
        try:
            data = tomllib.loads(manifest.read_text(encoding="utf-8"))
        except (tomllib.TOMLDecodeError, OSError):
            continue
        pkg = data.get("package")
        if not pkg or "name" not in pkg:
            continue
        version = pkg.get("version")
        if isinstance(version, dict) and version.get("workspace"):
            version = None
            for root, ver in workspace_versions.items():
                if root == manifest.parent or root in manifest.parents:
                    version = ver
        if not isinstance(version, str):
            version = None
        rel = manifest.parent.relative_to(ATLAS_ROOT)

        packages[pkg["name"]] = (rel, version)
    return packages


def iter_dependency_tables(data: dict):
    for key in ("dependencies", "dev-dependencies", "build-dependencies"):
        table = data.get(key)
        if isinstance(table, dict):
            yield table
    ws = data.get("workspace", {})
    if isinstance(ws.get("dependencies"), dict):
        yield ws["dependencies"]
    for target in (data.get("target") or {}).values():
        if isinstance(target, dict):
            for key in ("dependencies", "dev-dependencies", "build-dependencies"):
                if isinstance(target.get(key), dict):
                    yield target[key]


def normalize_url(url: str) -> str:
    return url.rstrip("/")


def collect_first_party_deps() -> list[tuple[str, str, str | None, Path]]:
    """Every first-party git dependency declared anywhere in the stack.

    Returns (package name, git url, version requirement or None, manifest).
    """
    found: list[tuple[str, str, str | None, Path]] = []
    manifests = repo_manifests()

    for manifest in sorted(set(manifests)):
        try:
            data = tomllib.loads(manifest.read_text(encoding="utf-8"))
        except (tomllib.TOMLDecodeError, OSError):
            continue
        for table in iter_dependency_tables(data):
            for name, spec in table.items():
                if not isinstance(spec, dict):
                    continue
                url = spec.get("git")
                if not isinstance(url, str) or FIRST_PARTY_HOST not in url:
                    continue
                pkg = spec.get("package", name)
                found.append((pkg, normalize_url(url), spec.get("version"), manifest))
    return found


def build_overlay(packages: dict[str, tuple[Path, str | None]]) -> tuple[str, list[str]]:
    """Emit the `[patch]` block, grouping local packages under each git URL."""
    by_url: dict[str, set[str]] = {}
    missing: list[str] = []

    for pkg, url, _req, _manifest in collect_first_party_deps():
        if pkg not in packages:
            missing.append(f"{pkg} (declared from {url})")
            continue
        by_url.setdefault(url, set()).add(pkg)

    # Cargo matches the source URL literally, so a repo referenced both with and
    # without the `.git` suffix, or with different casing, needs each form.
    # Normalize to the stem before emitting variants: appending to an input
    # that already carries the suffix minted dead `.git.git` keys.
    for url in list(by_url):
        stem = url.removesuffix(".git")
        for variant in (stem, stem + ".git"):
            if variant != url:
                by_url.setdefault(variant, set()).update(by_url[url])

    lines: list[str] = []
    for url in sorted(by_url, key=str.lower):
        lines.append(f'\n[patch."{url}"]')
        for pkg in sorted(by_url[url]):
            rel = packages[pkg][0].as_posix()
            lines.append(f'{pkg} = {{ path = "{rel}" }}')
    return "\n".join(lines) + "\n", sorted(set(missing))


def write_overlay(block: str) -> None:
    text = CONFIG.read_text(encoding="utf-8")
    generated = f"{HEADER}{block}{END}\n"
    if BEGIN in text and END in text:
        text = re.sub(
            re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?",
            generated,
            text,
            flags=re.DOTALL,
        )
    else:
        text = text.rstrip("\n") + "\n\n" + generated
    CONFIG.write_text(text, encoding="utf-8")


def set_enabled(enabled: bool) -> None:
    """Comment or uncomment the generated block.

    A provider-graph refresh (`cargo update` onto current git heads, which is
    what keeps a member's committed lock a valid release artifact) must resolve
    against git, not the local trees -- otherwise the overlay writes path
    entries into the lock. Disable, refresh, commit, re-enable.
    """
    text = CONFIG.read_text(encoding="utf-8")
    match = re.search(re.escape(BEGIN) + r"(.*?)" + re.escape(END), text, re.DOTALL)
    if not match:
        raise SystemExit("no generated overlay block found; run `generate` first")
    body = match.group(1)
    lines = []
    for line in body.split("\n"):
        stripped = line.lstrip()
        is_off = stripped.startswith("#OFF#")
        if enabled and is_off:
            lines.append(stripped.removeprefix("#OFF#"))
        elif not enabled and not is_off and stripped and not stripped.startswith("#"):
            lines.append("#OFF#" + line)
        else:
            lines.append(line)
    CONFIG.write_text(text.replace(body, "\n".join(lines)), encoding="utf-8")


def satisfies(version: str, requirement: str) -> bool:
    """Caret-semantics check: does `version` satisfy `requirement`?

    Covers the requirement forms the stack actually declares (`*`, bare
    `1.2.3`, and explicit `^`). Anything else is reported as unknown rather
    than silently passed.
    """
    requirement = requirement.strip()
    if requirement in ("*", ""):
        return True
    if requirement[0] in "<>=~":
        return True  # not used in-stack; do not guess
    req = requirement.removeprefix("^")

    def parts(text: str) -> list[int]:
        out = []
        for chunk in text.split("-")[0].split("."):
            try:
                out.append(int(chunk))
            except ValueError:
                out.append(0)
        while len(out) < 3:
            out.append(0)
        return out[:3]

    have, want = parts(version), parts(req)
    if have < want:
        return False
    # Caret: leading nonzero component must match.
    for i in range(3):
        if want[i] != 0:
            return have[:i + 1] == want[:i + 1]
    return True


def check_locks(packages: dict[str, tuple[Path, str | None]]) -> list[str]:
    """Report committed locks that pin a first-party version the local tree no
    longer provides.

    This is the failure the overlay actually hits. A requirement can be
    perfectly satisfiable while the committed `Cargo.lock` still pins an older
    provider version; Cargo then refuses the patch with "candidate versions
    found which didn't match", which reads as a resolver mystery rather than
    the pin drift it is.
    """
    drift: list[str] = []
    for lock in sorted(REPOS.glob("*/Cargo.lock")):
        if _skip(lock):
            continue
        try:
            data = tomllib.loads(lock.read_text(encoding="utf-8"))
        except (tomllib.TOMLDecodeError, OSError):
            continue
        rel = lock.relative_to(ATLAS_ROOT).as_posix()
        for pkg in data.get("package", []):
            if FIRST_PARTY_HOST not in pkg.get("source", ""):
                continue
            name, locked = pkg.get("name"), pkg.get("version")
            local = packages.get(name, (None, None))[1]
            if local is not None and locked != local:
                drift.append(f"{rel}: `{name}` locked {locked}, local tree {local}")
    return drift


def check(packages: dict[str, tuple[Path, str | None]]) -> int:
    lag: list[str] = []
    unresolved: list[str] = []

    for pkg, url, req, manifest in collect_first_party_deps():
        rel = manifest.relative_to(ATLAS_ROOT).as_posix()
        if pkg not in packages:
            unresolved.append(f"{rel}: `{pkg}` from {url} has no local working tree")
            continue
        local_version = packages[pkg][1]
        if req is None or local_version is None:
            continue
        if not satisfies(local_version, req):
            lag.append(
                f"{rel}: requires `{pkg} = \"{req}\"` but the local tree is "
                f"{local_version} -- the overlay cannot unify this edge"
            )

    for line in sorted(set(unresolved)):
        print(f"unresolved: {line}")
    for line in sorted(set(lag)):
        print(f"REQUIREMENT LAG: {line}")

    drift = check_locks(packages)
    by_repo: dict[str, list[str]] = {}
    for line in sorted(set(drift)):
        by_repo.setdefault(line.split(":", 1)[0], []).append(line.split(": ", 1)[1])
    for repo, entries in sorted(by_repo.items()):
        print(f"\nPIN DRIFT: {repo} ({len(entries)})")
        for entry in entries:
            print(f"  {entry}")

    if lag or drift:
        print(
            f"\n{len(set(lag))} lagging requirement(s), "
            f"{len(by_repo)} repo(s) with pin drift.\n"
            "Requirement lag: advance the consumer requirement to the provider's "
            "current workspace version.\n"
            "Pin drift: run `cargo update` in the repo to re-resolve onto the "
            "current provider heads, then verify and commit the lock."
        )
        return 1
    print("stack aligned: requirements satisfiable and locks match the local trees")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("generate", "check", "off", "on"))
    args = parser.parse_args()

    packages = load_packages()
    if args.mode in ("off", "on"):
        set_enabled(args.mode == "on")
        state = "enabled" if args.mode == "on" else "disabled"
        print(f"overlay {state}")
        if args.mode == "off":
            print("first-party deps now resolve from git; re-enable with `on` "
                  "once the provider-graph refresh is committed")
        return 0
    if args.mode == "generate":
        block, missing = build_overlay(packages)
        write_overlay(block)
        count = block.count("[patch.")
        print(f"wrote {count} patch sections to {CONFIG.relative_to(ATLAS_ROOT)}")
        for item in missing:
            print(f"skipped (no local tree): {item}")
        return 0
    return check(packages)


if __name__ == "__main__":
    sys.exit(main())
