"""Shared target-cache path and generated lane configuration helpers."""

from __future__ import annotations

import pathlib
import subprocess


MARKER = "# generated by scripts/atlas-member-target-dir.py"


def git_common_dir(checkout: pathlib.Path) -> pathlib.Path:
    """Return the absolute common Git directory for ``checkout``."""
    try:
        result = subprocess.run(
            [
                "git", "rev-parse", "--path-format=absolute", "--show-toplevel",
                "--git-common-dir",
            ],
            cwd=checkout,
            check=True,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError) as error:
        raise RuntimeError(f"cannot resolve Git common directory from {checkout}") from error
    lines = result.stdout.splitlines()
    if len(lines) != 2 or pathlib.Path(lines[0]).resolve() != checkout.resolve():
        raise RuntimeError(f"cannot resolve Git common directory from {checkout}")
    common_dir = pathlib.Path(lines[1]).resolve()
    if common_dir.name.casefold() != ".git":
        raise RuntimeError(f"unexpected Git common directory: {common_dir}")
    return common_dir


def shared_target_for(checkout: pathlib.Path) -> pathlib.Path:
    """Return the target cache beside the checkout's common Git directory."""
    return git_common_dir(checkout).parent / "target"


def lane_config(root: pathlib.Path) -> pathlib.Path:
    """Return the generated config inherited by every canonical lane."""
    return root / "worktrees" / ".cargo" / "config.toml"


def lane_config_text(root: pathlib.Path) -> str:
    """Render the lane config for the Atlas root's shared target cache."""
    target = shared_target_for(root).as_posix()
    return f"""{MARKER}
#
# This config is inherited by every linked lane below worktrees/. Cargo
# resolves relative target directories from each lane's workspace root, so the
# absolute path keeps lane builds on the Atlas root cache.
[build]
target-dir = \"{target}\"
"""


def ensure_lane_config(root: pathlib.Path) -> pathlib.Path:
    """Create or refresh the lane config, refusing an unrelated file."""
    path = lane_config(root)
    expected = lane_config_text(root)
    if path.exists():
        actual = path.read_text(encoding="utf-8").replace("\r\n", "\n")
        if MARKER not in actual:
            raise RuntimeError(f"{path} exists and is not generated by Atlas")
        if actual != expected:
            path.write_text(expected, encoding="utf-8", newline="\n")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8", newline="\n")
    return path
