"""Shared target-cache path and generated Cargo configuration helpers.

Two generated files keep builds on the one shared cache: the member pin
(``repos/.cargo/config.toml``) and the lane config
(``worktrees/.cargo/config.toml``). This module owns their text, their
refresh, and the scan for anything that would redirect a lane's build output.
"""

from __future__ import annotations

import os
import pathlib
import stat
import subprocess
import tomllib
from collections.abc import Iterator, Mapping
from typing import NamedTuple


MARKER = "# generated by scripts/atlas-member-target-dir.py"
CACHE_TAG = "CACHEDIR.TAG"
# The line Cargo writes into the tag of every directory it creates. Other
# tools (pytest, ruff, mypy) write the same signature with their own name.
CARGO_TAG = "# This file is a cache directory tag created by cargo."
CONFIG_NAMES = ("config.toml", "config")
# `build.target-dir` and `build.build-dir` are Cargo's two output roots; a
# lane that redirects either leaves the shared cache.
OUTPUT_KEYS = ("target-dir", "build-dir")
TARGET_ENVIRONMENT = (
    "CARGO_TARGET_DIR", "CARGO_BUILD_TARGET_DIR", "CARGO_BUILD_BUILD_DIR",
)
# Children of the lane root that are not lanes.
NON_LANE_CHILDREN = frozenset({".cargo", ".archive"})


class LaneScan(NamedTuple):
    """Cargo cache redirections found inside one lane checkout."""

    overrides: list[pathlib.Path]
    cache_dirs: list[pathlib.Path]


def _includes(path: pathlib.Path, data: Mapping[str, object]) -> Iterator[pathlib.Path]:
    """Yield the files a Cargo config includes.

    An include path is relative to the directory of the file that names it.
    Cargo rejects a malformed or absent required include itself, so those are
    skipped here.
    """
    raw = data.get("include", [])
    for entry in raw if isinstance(raw, list) else [raw]:
        if isinstance(entry, str):
            yield path.parent / entry
        elif isinstance(entry, dict) and isinstance(entry.get("path"), str):
            yield path.parent / entry["path"]


def target_dir_declaration(
    path: pathlib.Path, seen: set[pathlib.Path] | None = None
) -> str | None:
    """Explain how a Cargo config redirects its output directories, or return ``None``.

    ``build.target-dir`` and ``build.build-dir`` both count. The structure is
    parsed, so dotted, quoted, and inline keys count, and each ``include`` is
    followed. A file that cannot be read or parsed is reported: Cargo may
    still obey a config this tool cannot read.
    """
    visited = set() if seen is None else seen
    resolved = path.resolve()
    if resolved in visited:
        return None
    visited.add(resolved)
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return "cannot be read or parsed"
    build = data.get("build")
    if isinstance(build, dict):
        for key in OUTPUT_KEYS:
            if key in build:
                return f"declares build.{key}"
    for included in _includes(path, data):
        if included.is_file():
            reason = target_dir_declaration(included, visited)
            if reason is not None:
                return f"includes {included.as_posix()}, which {reason}"
    return None


def declares_target_dir(path: pathlib.Path) -> bool:
    """Return whether a Cargo config redirects ``build.target-dir`` or ``build.build-dir``."""
    return target_dir_declaration(path) is not None


def git_common_dir(checkout: pathlib.Path) -> pathlib.Path:
    """Return the absolute common Git directory for ``checkout``."""
    try:
        result = subprocess.run(
            [
                "git", "rev-parse", "--path-format=absolute", "--show-toplevel",
                "--git-common-dir",
            ],
            cwd=checkout,
            check=True,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=10,
        )
    except (OSError, subprocess.SubprocessError) as error:
        raise RuntimeError(f"cannot resolve Git common directory from {checkout}") from error
    lines = result.stdout.splitlines()
    if len(lines) != 2 or pathlib.Path(lines[0]).resolve() != checkout.resolve():
        raise RuntimeError(f"cannot resolve Git common directory from {checkout}")
    common_dir = pathlib.Path(lines[1]).resolve()
    if common_dir.name.casefold() != ".git":
        raise RuntimeError(f"unexpected Git common directory: {common_dir}")
    return common_dir


def shared_target_for(checkout: pathlib.Path) -> pathlib.Path:
    """Return the target cache beside the checkout's common Git directory."""
    return git_common_dir(checkout).parent / "target"


def lane_config(root: pathlib.Path) -> pathlib.Path:
    """Return the generated config inherited by every lane under ``worktrees/``."""
    return root / "worktrees" / ".cargo" / "config.toml"


def lane_legacy_config(root: pathlib.Path) -> pathlib.Path:
    """Return Cargo's legacy config path beside the generated lane config."""
    return root / "worktrees" / ".cargo" / "config"


def member_config(root: pathlib.Path) -> pathlib.Path:
    """Return the generated pin that sits between every member and the stack root."""
    return root / "repos" / ".cargo" / "config.toml"


def _redirects(path: pathlib.Path) -> bool:
    """Whether ``path`` is a symlink or junction, which a lane scan never follows.

    A junction is a Windows reparse point; ``os.path.isjunction`` needs Python
    3.12, so the file attribute is read directly.
    """
    if path.is_symlink():
        return True
    try:
        attributes = getattr(os.lstat(path), "st_file_attributes", 0)
    except OSError:
        return True
    return bool(attributes & stat.FILE_ATTRIBUTE_REPARSE_POINT)


def _cargo_output_dir(
    here: pathlib.Path, dirnames: list[str], filenames: list[str]
) -> bool:
    """Whether ``here`` is a directory Cargo builds into.

    The tag says which tool wrote it, since pytest, ruff, and mypy write one
    too. A directory without a tag is recognized by Cargo's own layout.
    """
    if CACHE_TAG in filenames:
        try:
            text = (here / CACHE_TAG).read_text(encoding="utf-8", errors="replace")
        except OSError:
            return True
        return CARGO_TAG in text
    if ".rustc_info.json" in filenames:
        return True
    return any(
        (here / profile / ".fingerprint").is_dir()
        for profile in ("debug", "release")
        if profile in dirnames
    )


def scan_lane(lane: pathlib.Path) -> LaneScan:
    """Find what inside ``lane`` can send a Cargo build away from the shared cache.

    ``overrides`` lists every ``.cargo/config{,.toml}`` at any depth that
    redirects ``build.target-dir`` or ``build.build-dir``, directly or through
    an ``include``: Cargo reads the configs above its working directory, so a
    nested one applies to builds started below it. ``cache_dirs`` lists every
    directory Cargo built into, at any depth (``crates/foo/target`` appears
    when a build starts there with a relative ``CARGO_TARGET_DIR``); the walk
    does not descend below one. Git metadata, symlinks, and junctions are not
    entered.
    """
    overrides: list[pathlib.Path] = []
    cache_dirs: list[pathlib.Path] = []
    for current, dirnames, filenames in os.walk(lane):
        here = pathlib.Path(current)
        if _cargo_output_dir(here, dirnames, filenames):
            cache_dirs.append(here)
            dirnames.clear()
            continue
        if here.name == ".cargo":
            overrides.extend(
                here / name
                for name in CONFIG_NAMES
                if name in filenames and declares_target_dir(here / name)
            )
        dirnames[:] = sorted(
            name for name in dirnames if name != ".git" and not _redirects(here / name)
        )
    return LaneScan(sorted(overrides), sorted(cache_dirs))


def lane_checkouts(root: pathlib.Path) -> list[pathlib.Path]:
    """List the lanes under ``worktrees/``: the children holding a ``.git`` entry.

    Scratch directories such as run output are not lanes; the lane audit
    reports them separately.
    """
    worktrees = root / "worktrees"
    if not worktrees.is_dir():
        return []
    return [
        child for child in sorted(worktrees.iterdir())
        if child.is_dir()
        and child.name not in NON_LANE_CHILDREN
        and (child / ".git").exists()
    ]


def lane_target_overrides(root: pathlib.Path) -> list[pathlib.Path]:
    """Find output-directory overrides in every lane under ``worktrees/`` and the legacy config."""
    overrides = []
    legacy = lane_legacy_config(root)
    if legacy.is_file():
        overrides.append(legacy)
    for lane in lane_checkouts(root):
        overrides.extend(scan_lane(lane).overrides)
    return overrides


def environment_target_overrides(
    environ: Mapping[str, str], shared: pathlib.Path
) -> list[str]:
    """Name the Cargo output variables in ``environ`` that leave ``shared``.

    Cargo resolves a relative value against its working directory, so inside a
    lane it forks the cache; an absolute value is accepted only when it is the
    shared target. A relative value is rejected on its own, even when it would
    resolve to the shared target from the current directory. Config files
    cannot see the environment, so the lane audit reads it.
    """
    found = []
    for name in TARGET_ENVIRONMENT:
        value = environ.get(name)
        if value and (
            not pathlib.Path(value).is_absolute()
            or os.path.normcase(os.path.realpath(value))
            != os.path.normcase(os.path.realpath(shared))
        ):
            found.append(f"{name}={value}")
    return found


def lane_config_text(root: pathlib.Path) -> str:
    """Render the lane config for the Atlas root's shared target cache."""
    target = shared_target_for(root).as_posix()
    return f"""{MARKER}
#
# Inherited by every linked lane below worktrees/. The path is absolute
# because `worktrees/` may sit inside a linked worktree of the stack
# repository, where a relative path would name that worktree's own target
# directory instead of the primary checkout's. A relative path resolves
# against the parent of the directory holding the file that declares it. The
# lane audit rejects any closer config, include, or lane-local target
# directory that would redirect it.
[build]
target-dir = "{target}"
"""


MEMBER_TEMPLATE = MARKER + """
#
# Cargo resolves `build.target-dir` relative to the workspace root, not to the
# config that declares it, so the stack root's relative `target-dir = "target"`
# only reaches the shared cache for builds rooted at the stack root. Inside a
# member the workspace root is the member, and the same line would resolve to
# that member's own `target/`.
#
# This file sits between every member and the stack root: cargo merges configs
# from the invocation directory upward, so it is closer than the root and
# outside every member -- which matters, because several members carry a
# tracked `.cargo/config.toml` of their own that this must not touch.
#
# Absolute because that is the only value that survives both roots, and
# gitignored because an absolute path is machine-specific. Delete it and
# in-member builds fork the cache again. Regenerate with
# `python scripts/atlas-member-target-dir.py generate`.
[build]
target-dir = "{target}"
"""


def member_config_text(root: pathlib.Path) -> str:
    """Render the member pin for the Atlas root's shared target cache."""
    return MEMBER_TEMPLATE.format(target=shared_target_for(root).as_posix())


def _ensure_generated(path: pathlib.Path, expected: str) -> pathlib.Path:
    """Create or refresh a generated config, refusing an unrelated file."""
    if path.exists():
        actual = path.read_text(encoding="utf-8", errors="replace").replace("\r\n", "\n")
        if MARKER not in actual:
            raise RuntimeError(f"{path} exists and is not generated by Atlas")
        if actual != expected:
            path.write_text(expected, encoding="utf-8", newline="\n")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8", newline="\n")
    return path


def ensure_lane_config(root: pathlib.Path) -> pathlib.Path:
    """Create or refresh the lane config, refusing an unrelated file."""
    legacy = lane_legacy_config(root)
    if legacy.is_file():
        raise RuntimeError(f"{legacy} shadows the generated TOML config")
    return _ensure_generated(lane_config(root), lane_config_text(root))


def ensure_member_config(root: pathlib.Path) -> pathlib.Path:
    """Create or refresh the member pin, refusing an unrelated file."""
    return _ensure_generated(member_config(root), member_config_text(root))


def generation_refusal(root: pathlib.Path) -> str | None:
    """Explain why the generated configs cannot be written, or return ``None``.

    The one check `generate` and `create` apply before either file is
    touched: an unrelated file at either generated path, a lane config that
    declares ``target-dir`` or ``build-dir``, or a legacy lane config would
    leave builds off the shared cache or overwrite a file Atlas did not write.
    A checkout whose shared target cannot be resolved is refused here too, so
    the failure surfaces before a lane exists rather than after it.
    """
    overrides = lane_target_overrides(root)
    if overrides:
        return (
            "a Cargo config that declares target-dir or build-dir, or a legacy "
            "lane config, would fork the shared cache: "
            + ", ".join(path.as_posix() for path in overrides)
            + "; remove it first"
        )
    for path in (member_config(root), lane_config(root)):
        if path.exists() and MARKER not in path.read_text(encoding="utf-8", errors="replace"):
            return f"{path} exists and this tool did not write it -- left alone"
    try:
        shared_target_for(root)
    except RuntimeError as error:
        return str(error)
    return None
