#!/usr/bin/env python3
"""Generate and verify the Atlas stack development overlay.

The overlay is the single `[patch]` block in the stack-root `.cargo/config.toml`
that redirects first-party git dependencies to the local working trees. It lives
at the root because a `[patch]` section in a *member* manifest is only honored
when that member is the root of the build -- Cargo ignores it whenever the
member is consumed as a dependency. A root config `[patch]` applies to every
build beneath the root, which is the actual requirement.

Member manifests therefore keep their `git + version` sources and stay
consumable as git dependencies; this file owns local resolution.

Two modes:

    generate  rewrite the overlay block in .cargo/config.toml from the real
              repository layout (never hand-curated); emit compatible local
              candidates while older incompatible requirements retain git
              resolution
    check     report version lag -- every first-party requirement that the
              current local trees cannot satisfy. A patch only unifies when the
              local version satisfies the declared requirement, so lag is what
              produces the "local X cannot replace git-sourced Y" resolver
              failure.

Exit status is nonzero when `check` finds lag, so CI can gate on it.
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from atlas_stack import registered_member_names  # noqa: E402

ATLAS_ROOT = Path(__file__).resolve().parent.parent
REPOS = ATLAS_ROOT / "repos"
CONFIG = ATLAS_ROOT / ".cargo" / "config.toml"

BEGIN = "# >>> atlas stack development overlay (generated) >>>"
END = "# <<< atlas stack development overlay (generated) <<<"

FIRST_PARTY_HOST = "github.com/ryancinsight/"

HEADER = f"""{BEGIN}
# Generated by scripts/atlas-stack-overlay.py -- do not hand-edit.
#
# Redirects every first-party git dependency to its local working tree, for all
# builds rooted anywhere beneath the Atlas root. Member manifests keep their
# `git + version` sources, so each repository still resolves standalone and in
# CI exactly as published.
#
# A `[patch]` section committed in a member manifest does NOT do this: Cargo
# honors manifest patches only in the root manifest of the build, so such a
# block is inert for every downstream consumer while making the member
# unconsumable as a clean git dependency.
#
# A local candidate is emitted for each source with a compatible consumer.
# Cargo keeps incompatible requirements on their original git version; one
# lagging consumer must not prevent current consumers from sharing local types.
# Providers whose own workspace edges lag remain quarantined on git. `check`
# reports all incompatible requirements so their consumers can advance them.
#
# Local builds rewrite member `Cargo.lock` files (the `source` line is dropped
# and `[[patch.unused]]` entries appear). That churn is a development artifact:
# never commit it. Release and CI resolution is verified with `--locked` from a
# clean checkout, where this overlay does not apply.
#
# Regenerate:  python scripts/atlas-stack-overlay.py generate
# Check lag:   python scripts/atlas-stack-overlay.py check
"""


def _skip(path: Path) -> bool:
    """Whether a discovered manifest lies outside the canonical source view.

    worktrees is filtered here, not merely by where the glob is rooted: a
    lane opened *inside* a member repo (repos/<member>/worktrees/...) is
    still under that repo and would otherwise be globbed. Being sorted after
    crates/ it would then overwrite the canonical entry, pinning the whole
    stack to one agent's lane -- and to a dangling path the moment that lane is
    removed.
    """
    parts = {p.lower() for p in path.parts}
    return bool(parts & {"target", ".git", "node_modules", "worktrees"})


def repo_manifests() -> list[Path]:
    """Return manifests from the authoritative registered-repo namespace only.

    ``worktrees/`` and other lane copies are intentionally excluded: the root
    overlay is a development view of the canonical ``repos/`` checkouts, not a
    package resolver for alternate working copies.
    """
    manifests: set[Path] = set()
    for member in registered_member_names():
        root = REPOS / member
        if not root.is_dir():
            continue
        manifests.update(
            manifest for manifest in root.glob("**/Cargo.toml") if not _skip(manifest)
        )
    return sorted(manifests)


def load_packages() -> dict[str, tuple[Path, str | None]]:
    """Map local package name -> (path relative to ATLAS_ROOT, version)."""
    packages: dict[str, tuple[Path, str | None]] = {}
    workspace_versions: dict[Path, str] = {}

    manifests = repo_manifests()

    for manifest in sorted(set(manifests)):
        try:
            data = tomllib.loads(manifest.read_text(encoding="utf-8"))
        except (tomllib.TOMLDecodeError, OSError):
            continue
        ws = data.get("workspace", {}).get("package", {})
        if "version" in ws:
            workspace_versions[manifest.parent] = ws["version"]

    for manifest in sorted(set(manifests)):
        try:
            data = tomllib.loads(manifest.read_text(encoding="utf-8"))
        except (tomllib.TOMLDecodeError, OSError):
            continue
        pkg = data.get("package")
        if not pkg or "name" not in pkg:
            continue
        version = pkg.get("version")
        if isinstance(version, dict) and version.get("workspace"):
            version = None
            for root, ver in workspace_versions.items():
                if root == manifest.parent or root in manifest.parents:
                    version = ver
        if not isinstance(version, str):
            version = None
        rel = manifest.parent.relative_to(ATLAS_ROOT)

        packages[pkg["name"]] = (rel, version)
    return packages


def iter_dependency_tables(data: dict):
    for key in ("dependencies", "dev-dependencies", "build-dependencies"):
        table = data.get(key)
        if isinstance(table, dict):
            yield table
    ws = data.get("workspace", {})
    if isinstance(ws.get("dependencies"), dict):
        yield ws["dependencies"]
    for target in (data.get("target") or {}).values():
        if isinstance(target, dict):
            for key in ("dependencies", "dev-dependencies", "build-dependencies"):
                if isinstance(target.get(key), dict):
                    yield target[key]


def normalize_url(url: str) -> str:
    return url.rstrip("/")


def collect_first_party_deps() -> list[tuple[str, str, str | None, Path]]:
    """Every first-party git dependency declared anywhere in the stack.

    Returns (package name, git url, version requirement or None, manifest).
    """
    found: list[tuple[str, str, str | None, Path]] = []
    manifests = repo_manifests()

    for manifest in sorted(set(manifests)):
        try:
            data = tomllib.loads(manifest.read_text(encoding="utf-8"))
        except (tomllib.TOMLDecodeError, OSError):
            continue
        for table in iter_dependency_tables(data):
            for name, spec in table.items():
                if not isinstance(spec, dict):
                    continue
                url = spec.get("git")
                if not isinstance(url, str) or FIRST_PARTY_HOST not in url:
                    continue
                pkg = spec.get("package", name)
                found.append((pkg, normalize_url(url), spec.get("version"), manifest))
    return found


def package_repo(path: Path) -> Path:
    """Return the canonical ``repos/<repository>`` prefix for a package."""
    parts = path.parts
    return Path(*parts[:2]) if len(parts) >= 2 else path


def local_dependency_lags(
    packages: dict[str, tuple[Path, str | None]],
) -> dict[Path, set[str]]:
    """Find local provider repositories with incompatible workspace edges.

    A package can satisfy its consumer's version pin while its local workspace
    manifest still requests an older first-party provider. Patching that one
    package would then mix a local provider graph with the current locked Git
    graph. Leave the whole repository on Git until its workspace requirements
    advance together.
    """
    lags: dict[Path, set[str]] = {}
    for _package, (relative, _version) in packages.items():
        manifest = ATLAS_ROOT / relative / "Cargo.toml"
        try:
            data = tomllib.loads(manifest.read_text(encoding="utf-8"))
        except (tomllib.TOMLDecodeError, OSError):
            continue
        workspace_dependencies: dict = {}
        for parent in (manifest.parent, *manifest.parents):
            root_manifest = parent / "Cargo.toml"
            try:
                root_data = tomllib.loads(root_manifest.read_text(encoding="utf-8"))
            except (tomllib.TOMLDecodeError, OSError):
                continue
            workspace = root_data.get("workspace", {})
            if isinstance(workspace, dict) and isinstance(
                workspace.get("dependencies"), dict
            ):
                workspace_dependencies = workspace["dependencies"]
                break
        if not workspace_dependencies:
            continue
        for table in iter_dependency_tables(data):
            for name, spec in table.items():
                if not isinstance(spec, dict):
                    continue
                resolved = workspace_dependencies.get(name, spec) if spec.get("workspace") else spec
                if not isinstance(resolved, dict):
                    continue
                url = resolved.get("git")
                requirement = resolved.get("version")
                dependency = resolved.get("package", name)
                if (
                    not isinstance(url, str)
                    or FIRST_PARTY_HOST not in url
                    or not isinstance(requirement, str)
                ):
                    continue
                local = packages.get(dependency)
                if local is None or local[1] is None or satisfies(local[1], requirement):
                    continue
                repo = package_repo(relative)
                lags.setdefault(repo, set()).add(
                    f"{dependency} {requirement} (local {local[1]})"
                )
    return lags


def build_overlay(
    packages: dict[str, tuple[Path, str | None]],
) -> tuple[str, list[str], list[str]]:
    """Emit the `[patch]` block, grouping local packages under each git URL.

    Cargo adds patched versions to a source's candidates; it does not replace
    incompatible versions. Emit a package for a source when at least one of
    that source's declared requirements accepts the local version. Report
    incompatible consumers without letting them split a current consumer's
    direct Git and transitive local copies of the same package.

    Cargo Book, "Prepublishing a breaking change":
    https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#prepublishing-a-breaking-change
    The real Cargo fixture in test_atlas_stack_overlay.py resolves ^0.5 at its
    old Git revision alongside one local ^0.6 identity shared by the current
    direct dependency and its local transport dependency. Provider-workspace
    lag quarantine remains separate: those path edges change the local graph.
    """
    by_url: dict[str, set[str]] = {}
    missing: list[str] = []
    lag: list[str] = []

    reqs_by_pkg: dict[str, dict[str, list[str | None]]] = {}
    for pkg, url, req, _manifest in collect_first_party_deps():
        reqs_by_pkg.setdefault(pkg, {}).setdefault(url, []).append(req)

    repository_lags = local_dependency_lags(packages)
    for repo, edges in sorted(repository_lags.items()):
        lag.append(
            f"{repo.as_posix()}: local workspace edges {sorted(edges)!r}; "
            "leaving the repository packages on git"
        )

    for pkg, sources in sorted(reqs_by_pkg.items()):
        if pkg not in packages:
            missing.append(f"{pkg} (declared from {sorted(sources)[0]})")
            continue
        local_version = packages[pkg][1]
        for url, reqs in sorted(sources.items()):
            unsatisfied = [
                req
                for req in reqs
                if req is not None
                and local_version is not None
                and not satisfies(local_version, req)
            ]
            if unsatisfied:
                lag.append(
                    f"{pkg} ({url}): local tree is {local_version}, cannot satisfy "
                    f"{unsatisfied!r}; those requirements retain git resolution"
                )
            if len(unsatisfied) == len(reqs):
                continue
            if package_repo(packages[pkg][0]) in repository_lags:
                continue
            by_url.setdefault(url, set()).add(pkg)

    # Cargo matches the source URL literally, so a repo referenced both with and
    # without the `.git` suffix, or with different casing, needs each form.
    # Normalize to the stem before emitting variants: appending to an input
    # that already carries the suffix minted dead `.git.git` keys.
    for url in list(by_url):
        stem = url.removesuffix(".git")
        for variant in (stem, stem + ".git"):
            if variant != url:
                by_url.setdefault(variant, set()).update(by_url[url])

    lines: list[str] = []
    for url in sorted(by_url, key=str.lower):
        lines.append(f'\n[patch."{url}"]')
        for pkg in sorted(by_url[url]):
            rel = packages[pkg][0].as_posix()
            lines.append(f'{pkg} = {{ path = "{rel}" }}')
    return "\n".join(lines) + "\n", sorted(set(missing)), sorted(set(lag))


def write_overlay(block: str) -> None:
    text = CONFIG.read_text(encoding="utf-8")
    generated = f"{HEADER}{block}{END}\n"
    if BEGIN in text and END in text:
        text = re.sub(
            re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?",
            generated,
            text,
            flags=re.DOTALL,
        )
    else:
        text = text.rstrip("\n") + "\n\n" + generated
    CONFIG.write_text(text, encoding="utf-8")


def set_enabled(enabled: bool) -> None:
    """Comment or uncomment the generated block.

    A provider-graph refresh (`cargo update` onto current git heads, which is
    what keeps a member's committed lock a valid release artifact) must resolve
    against git, not the local trees -- otherwise the overlay writes path
    entries into the lock. Disable, refresh, commit, re-enable.
    """
    text = CONFIG.read_text(encoding="utf-8")
    match = re.search(re.escape(BEGIN) + r"(.*?)" + re.escape(END), text, re.DOTALL)
    if not match:
        raise SystemExit("no generated overlay block found; run `generate` first")
    body = match.group(1)
    lines = []
    for line in body.split("\n"):
        stripped = line.lstrip()
        is_off = stripped.startswith("#OFF#")
        if enabled and is_off:
            lines.append(stripped.removeprefix("#OFF#"))
        elif not enabled and not is_off and stripped and not stripped.startswith("#"):
            lines.append("#OFF#" + line)
        else:
            lines.append(line)
    CONFIG.write_text(text.replace(body, "\n".join(lines)), encoding="utf-8")


def satisfies(version: str, requirement: str) -> bool:
    """Caret-semantics check: does `version` satisfy `requirement`?

    Covers the requirement forms the stack actually declares (`*`, bare
    `1.2.3`, and explicit `^`). Anything else is reported as unknown rather
    than silently passed.
    """
    requirement = requirement.strip()
    if requirement in ("*", ""):
        return True
    if requirement[0] in "<>=~":
        return True  # not used in-stack; do not guess
    req = requirement.removeprefix("^")

    def parts(text: str) -> list[int]:
        out = []
        for chunk in text.split("-")[0].split("."):
            try:
                out.append(int(chunk))
            except ValueError:
                out.append(0)
        while len(out) < 3:
            out.append(0)
        return out[:3]

    have, want = parts(version), parts(req)
    if have < want:
        return False
    # Caret: leading nonzero component must match.
    for i in range(3):
        if want[i] != 0:
            return have[:i + 1] == want[:i + 1]
    return True


def check_locks(packages: dict[str, tuple[Path, str | None]]) -> list[str]:
    """Report committed locks that pin a first-party version the local tree no
    longer provides.

    This is the failure the overlay actually hits. A requirement can be
    perfectly satisfiable while the committed `Cargo.lock` still pins an older
    provider version; Cargo then refuses the patch with "candidate versions
    found which didn't match", which reads as a resolver mystery rather than
    the pin drift it is.
    """
    drift: list[str] = []
    for lock in sorted(REPOS.glob("*/Cargo.lock")):
        if _skip(lock):
            continue
        try:
            data = tomllib.loads(lock.read_text(encoding="utf-8"))
        except (tomllib.TOMLDecodeError, OSError):
            continue
        rel = lock.relative_to(ATLAS_ROOT).as_posix()
        for pkg in data.get("package", []):
            if FIRST_PARTY_HOST not in pkg.get("source", ""):
                continue
            name, locked = pkg.get("name"), pkg.get("version")
            local = packages.get(name, (None, None))[1]
            if local is not None and locked != local:
                drift.append(f"{rel}: `{name}` locked {locked}, local tree {local}")
    return drift


def _normalize(text: str) -> str:
    """Line endings and trailing space removed, so only content is compared."""
    return chr(10).join(line.rstrip() for line in text.replace(chr(13), "").split(chr(10))).strip()


def check_overlay_freshness(packages: dict[str, tuple[Path, str | None]]) -> list[str]:
    """Report a committed overlay that no longer matches the repository layout.

    Two failures this catches, both of which break every build in the stack
    before a single crate compiles:

    * a **dangling path** -- an entry pointing at a tree that has since been
      removed, which Cargo reports as an unreadable manifest rather than as a
      stale overlay;
    * **drift** from what the generator would emit now, which means the block
      was hand-edited or predates a layout change.

    Regenerate-and-diff is the generator contract; this is its executable form.
    """
    problems: list[str] = []
    text = CONFIG.read_text(encoding="utf-8")
    match = re.search(re.escape(BEGIN) + r"(.*?)" + re.escape(END), text, re.DOTALL)
    if not match:
        return ["no generated overlay block found; run `generate`"]

    # The block may be commented out (`off` mode); compare its content, not its
    # enabled state, so a deliberately disabled overlay is not reported as stale.
    committed = "\n".join(
        line.lstrip().removeprefix("#OFF#") if line.lstrip().startswith("#OFF#") else line
        for line in match.group(1).split("\n")
    )

    for rel in re.findall(r'path = "([^"]+)"', committed):
        if not (ATLAS_ROOT / rel / "Cargo.toml").is_file():
            problems.append(f"dangling overlay path `{rel}` -- no manifest there")

    # The config is checked out with platform line endings; the generator emits
    # LF. Compare content, not the endings git already normalizes.
    # `write_overlay` emits HEADER (which opens with BEGIN) followed by the
    # patch block, so the captured region is the header tail plus the block.
    expected, _missing, _lag = build_overlay(packages)
    expected_body = (HEADER + expected).split(BEGIN, 1)[1]
    if _normalize(committed) != _normalize(expected_body):
        problems.append(
            "overlay differs from a fresh generation -- run "
            "`python scripts/atlas-stack-overlay.py generate` and commit the result"
        )
    return sorted(set(problems))


def check(packages: dict[str, tuple[Path, str | None]]) -> int:
    lag: list[str] = []
    unresolved: list[str] = []

    for pkg, url, req, manifest in collect_first_party_deps():
        rel = manifest.relative_to(ATLAS_ROOT).as_posix()
        if pkg not in packages:
            unresolved.append(f"{rel}: `{pkg}` from {url} has no local working tree")
            continue
        local_version = packages[pkg][1]
        if req is None or local_version is None:
            continue
        if not satisfies(local_version, req):
            lag.append(
                f"{rel}: requires `{pkg} = \"{req}\"` but the local tree is "
                f"{local_version} -- the overlay cannot unify this edge"
            )

    for line in sorted(set(unresolved)):
        print(f"unresolved: {line}")
    for line in sorted(set(lag)):
        print(f"REQUIREMENT LAG: {line}")

    stale = check_overlay_freshness(packages)
    for line in stale:
        print(f"OVERLAY: {line}")

    drift = check_locks(packages)
    by_repo: dict[str, list[str]] = {}
    for line in sorted(set(drift)):
        by_repo.setdefault(line.split(":", 1)[0], []).append(line.split(": ", 1)[1])
    for repo, entries in sorted(by_repo.items()):
        print(f"\nPIN DRIFT: {repo} ({len(entries)})")
        for entry in entries:
            print(f"  {entry}")

    if lag or drift or stale:
        print(
            f"\n{len(set(lag))} lagging requirement(s), "
            f"{len(by_repo)} repo(s) with pin drift.\n"
            "Requirement lag: advance the consumer requirement to the provider's "
            "current workspace version.\n"
            "Pin drift: run `cargo update` in the repo to re-resolve onto the "
            "current provider heads, then verify and commit the lock.\n"
            "Overlay: regenerate and commit -- a stale or dangling entry fails "
            "every build in the stack at resolution time."
        )
        return 1
    print("stack aligned: requirements satisfiable and locks match the local trees")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("generate", "check", "off", "on"))
    args = parser.parse_args()

    packages = load_packages()
    if args.mode in ("off", "on"):
        set_enabled(args.mode == "on")
        state = "enabled" if args.mode == "on" else "disabled"
        print(f"overlay {state}")
        if args.mode == "off":
            print("first-party deps now resolve from git; re-enable with `on` "
                  "once the provider-graph refresh is committed")
        return 0
    if args.mode == "generate":
        block, missing, lag = build_overlay(packages)
        write_overlay(block)
        count = block.count("[patch.")
        print(f"wrote {count} patch sections to {CONFIG.relative_to(ATLAS_ROOT)}")
        for item in missing:
            print(f"skipped (no local tree): {item}")
        for item in lag:
            print(f"version lag (consumer must advance): {item}")
        return 0
    return check(packages)


if __name__ == "__main__":
    sys.exit(main())
